#pragma once

#define NO_ACTION_MACRO
#define TAPPING_TERM 170
#define TAPPING_TERM_PER_KEY

#define IGNORE_MOD_TAP_INTERRUPT

#define TAPPING_FORCE_HOLD

#define PERMISSIVE_HOLD

#define COMBO_VARIABLE_LEN
#define COMBO_COUNT COMBO_VARIABLE_LEN
#define COMBO_TERM 70

#define UNICODE_SELECTED_MODES UC_LNX, UC_WINC

